export const propertyData = [
  {
    id: 1,
    title: "Modern Apartment",
    address: "123 MG Road, Bengaluru",
    price: 8500000,
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: 1000,
  },
  {
    id: 2,
    title: "Cozy Cottage",
    address: "456 Neem Lane, Dehradun",
    price: 6500000,
    type: "House",
    bedrooms: 3,
    bathrooms: 1,
    area: 1200,
  },
  {
    id: 3,
    title: "Luxury Villa",
    address: "789 Palm Drive, Goa",
    price: 25000000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
  },
  {
    id: 4,
    title: "Urban Loft",
    address: "101 Andheri East, Mumbai",
    price: 12000000,
    type: "Loft",
    bedrooms: 1,
    bathrooms: 1,
    area: 800,
  },
  {
    id: 5,
    title: "Suburban Family Home",
    address: "202 Maple Street, Gurgaon",
    price: 18000000,
    type: "House",
    bedrooms: 4,
    bathrooms: 2.5,
    area: 2200,
  },
  {
    id: 6,
    title: "Beachfront Condo",
    address: "303 Marina Road, Kochi",
    price: 22000000,
    type: "Condo",
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
  },
  {
    id: 7,
    title: "Mountain Retreat",
    address: "404 Pine Hills, Shimla",
    price: 9500000,
    type: "Cabin",
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
  },
  {
    id: 8,
    title: "City Center Penthouse",
    address: "505 Connaught Place, Delhi",
    price: 55000000,
    type: "Penthouse",
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
  },
  {
    id: 9,
    title: "Countryside Farmhouse",
    address: "606 Farm Lane, Alibag",
    price: 15000000,
    type: "Farmhouse",
    bedrooms: 4,
    bathrooms: 2,
    area: 2600,
  },
];
